# Generated by Django 3.0.4 on 2020-03-26 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationdetails',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Donor'),
        ),
        migrations.AddConstraint(
            model_name='donationdetails',
            constraint=models.UniqueConstraint(fields=('donor', 'donation_type'), name='unique_donation'),
        ),
    ]
