<<<<<<< Updated upstream:donations/migrations/0002_auto_20200325_1353.py
# Generated by Django 3.0.4 on 2020-03-25 17:53
=======
# Generated by Django 3.0.4 on 2020-04-01 01:53
>>>>>>> Stashed changes:donations/migrations/0002_auto_20200331_2153.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
<<<<<<< Updated upstream:donations/migrations/0002_auto_20200325_1353.py
            name='id',
            field=models.AutoField(auto_created=True, default=9, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>>>>>>> Stashed changes:donations/migrations/0002_auto_20200331_2153.py
        ),
    ]
