# Generated by Django 3.0.4 on 2020-03-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20200326_2116'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='donationdetails',
            name='unique_donation',
        ),
        migrations.AddField(
            model_name='donationdetails',
            name='order',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
